In [1]:
import theano
import theano.tensor as T

x = T.matrix('x')
y = T.matrix('y')
z = T.matrix('z')

# (x+y) + (x+y) * z
a = x + y
b = a * z
c = a + b

f = theano.function(
    inputs = [x, y, z],
    outputs = c
)


Using gpu device 0: GeForce GTX TITAN X (CNMeM is disabled)


In [5]:
import numpy as np

xx = np.random.randn(4, 5).astype('float32')
yy = np.random.randn(4, 5).astype('float32')
zz = np.random.randn(4, 5).astype('float32')

print f(xx, yy, zz)

[[ 1.05651045 -1.21079338  1.23110497 -0.04195251  2.67902255]
 [-0.13276182  1.76614249 -0.36022687 -0.59106445 -2.71669126]
 [-2.37245154 -1.12027502  4.23539543 -5.01190567 -0.88961536]
 [ 0.09296193  0.19824572 -0.89048773  1.89251935  2.93632889]]
